
- name: play one
  hosts: lemp_server
  become: true
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: nginx install
      apt:
        name: nginx
        state: present

    - name: nginx start
      service:
        name: nginx
        state: started

    - name: php install
      apt:
        name: php
        state: present

    - name: php8.3-fpm install
      apt:
        name: php8.3-fpm
        state: present

    - name: php start
      service:
        name: php8.3-fpm
        state: started

    - name: mysql install
      apt:
        name: mysql-server
        state: present

    - name: mysql start
      service:
        name: mysql
        state: started

    - name: nginx restart
      service:
        name: nginx
        state: restarted

    - name: php restart
      service:
        name: php8.3-fpm
        state: restarted

    - name: mysql restart
      service:
        name: mysql
        state: restarted
